"""Deterministic paper edge-identity evidence (PRDV4 Stage 4 prerequisite, identity-only).

This validation artifact resolves a canonical, digest-bound paper ``edge_id`` for a paper evaluation from a
proven ``StrategySpec`` (and, optionally, a proven ``StrategySignalToPaperIntent`` bridge). It is paper-only,
deterministic, digest-bound, and fail-closed.

Governance (user-approved for this slice):

* ``paper_edge_id = sha256(canonical_json({"strategy_id": ..., "market_symbol": ...}))`` — a lowercase hex64,
  delimiter-free, collision-resistant digest; ``strategy_id`` and ``market_symbol`` are also bound separately as
  human-readable fields;
* the ``StrategySpec`` identity is proven by recomputing the PUBLIC ``strategy_spec_digest`` and requiring it to
  equal the caller anchor, plus a full ``validate_strategy_spec`` acceptance and a ``market_symbol`` membership
  check against the spec's ``instrument_universe``;
* an OPTIONAL ``StrategySignalToPaperIntent`` bridge upgrades the binding from
  ``STRATEGY_SPEC_DIGEST_BOUND`` to ``SPEC_DIGEST_AND_SIGNAL_BRIDGE_BOUND`` after its public digest is re-proven
  and its identity fields are cross-checked.

EXPLICIT LIMITATION (serializer-visible + digest-bound): the binding to the already-merged §10.4 / Sharpe paper
chain is ``correlation_and_market_only`` — those merged artifacts do NOT carry ``spec_digest``, so this artifact
does NOT cryptographically prove that the merged §10.4 / Sharpe chain was generated by this ``StrategySpec``.

It does NOT consume ``PaperSharpeEvidence`` / ``PaperVsBacktestMethodology`` / daily-return / 30-day-gate
evidence, does NOT bind a backtest baseline, does NOT invoke the Stage-4 comparator, does NOT construct
``Stage4PaperSummary`` / ``Stage4BacktestBaseline``, does NOT set ``prdv4_stage4_complete``, and does NOT prove
edge, profitability, comparison readiness, live readiness, shadow readiness, Deribit readiness, or operational
readiness. It calls no wall-clock, runtime, service, execution, venue, scheduler, filesystem, network, or random
surface.
"""

from __future__ import annotations

import hashlib
import json
import re
from collections.abc import Mapping
from dataclasses import dataclass
from enum import Enum

from crypto_core.strategy.spec import (
    StrategySpec,
    StrategySpecMarketType,
    strategy_spec_digest,
    strategy_spec_to_dict,
    validate_strategy_spec,
)
from crypto_core.validation.strategy_signal_to_paper_intent import (
    StrategySignalToPaperIntent,
    StrategySignalToPaperIntentStatus,
    strategy_signal_to_paper_intent_digest,
)

_SCHEMA_VERSION = "paper-edge-identity-evidence.v1"
_EVIDENCE_VERSION = "paper-edge-identity-evidence.v1"
_EDGE_ID_FORM = "hex64_sha256"
_EDGE_ID_DERIVATION_POLICY = "sha256_canonical_strategy_id_market_symbol.v1"
_EDGE_ID_DERIVATION_INPUTS = ("strategy_id", "market_symbol")
_BINDING_SPEC_ONLY = "STRATEGY_SPEC_DIGEST_BOUND"
_BINDING_SPEC_AND_BRIDGE = "SPEC_DIGEST_AND_SIGNAL_BRIDGE_BOUND"
_BINDING_UNRESOLVED = "UNRESOLVED"
_PAPER_CHAIN_LINK = "correlation_and_market_only"
_PAPER_CHAIN_LINK_LIMITATION = "merged_stage10_4_chain_does_not_carry_strategy_spec_digest.v1"
_SUPPORTED_MARKET_TYPES = frozenset(StrategySpecMarketType)

_SHA256_HEX_LENGTH = 64
_HEX_CHARS = frozenset("0123456789abcdef")
_BIST_PATTERN = re.compile(r"\b(?:bist\w*|borsa\w*|matriks\w*)|\bkap\b", re.IGNORECASE)
_FORBIDDEN_PATTERN = re.compile(
    r"(?<![A-Za-z0-9])orders?(?![A-Za-z0-9])"
    r"|\b(?:private|order_router|place_order|live_order|auto_loop|connector|connector_ready|"
    r"credential|credentials|scheduler|shadow|route_id|execution_instruction|deribit|"
    r"venue_order_id|exchange_order_id|client_order_id|readiness|service|real_money|paper_adapter|"
    r"stage4_comparator|compare_stage4|Stage4PaperSummary|Stage4BacktestBaseline|capital|margin|balance|"
    r"reservation|real_account_equity|account_equity|real_equity)\w*"
    r"|crypto_core\.(?:service|execution|venue|runtime|orchestrator|temporal|session|data|portfolio)\b"
    r"|\blive(?:\b|[_-]\w+)",
    re.IGNORECASE,
)
_SAFE_MARKET_DATA_TERMS = ("limit_order_book", "order_book", "order_flow")
_CLOCK_TOKENS = (
    "wall_clock",
    "wall-clock",
    "wallclock",
    "datetime.now",
    "datetime.utcnow",
    "utcnow",
    "time.time_ns",
    "time.time",
    "perf_counter",
    "monotonic",
    "server_time",
    "exchange_time",
    "live_time",
    "real_time",
    "realtime",
    "system_time",
    "clock",
    "now()",
)


class PaperEdgeIdentityEvidenceError(RuntimeError):
    """Raised on malformed caller input, forbidden scope/clock tokens, or optional-bridge argument misuse."""


class PaperEdgeIdentityEvidenceStatus(str, Enum):
    """Edge-identity evidence status. READY resolves an identity only — never an edge/comparison verdict."""

    READY = "READY"
    REJECTED = "REJECTED"


@dataclass(frozen=True)
class PaperEdgeIdentityEvidence:
    """Immutable, digest-bound paper edge-identity evidence (identity-only)."""

    schema_version: str
    evidence_version: str
    status: PaperEdgeIdentityEvidenceStatus
    ready: bool
    edge_identity_id: str
    paper_id: str
    correlation_id: str
    edge_identity_resolved: bool
    strategy_spec_identity_proven: bool
    signal_bridge_consumed: bool
    paper_edge_id: str
    edge_id_form: str
    edge_id_derivation_policy: str
    edge_id_derivation_inputs: tuple[str, ...]
    strategy_id: str
    strategy_version: str
    strategy_family: str
    edge_family: str
    market_type: str
    market_symbol: str
    expected_strategy_spec_digest: str
    verified_strategy_spec_digest: str
    signal_bridge_digest: str
    expected_signal_bridge_digest: str
    verified_signal_bridge_digest: str
    binding_strength: str
    paper_chain_link: str
    paper_chain_link_cryptographic: bool
    paper_chain_spec_digest_carried: bool
    paper_chain_link_limitation: str
    reason_codes: tuple[str, ...]
    metadata: tuple[tuple[str, str], ...]
    edge_identity_digest: str
    paper_only: bool = True
    edge_proven: bool = False
    profitability_proven: bool = False
    same_edge_as_backtest_proven: bool = False
    same_edge_comparison_ready: bool = False
    comparison_ready: bool = False
    paper_vs_backtest_comparison_ready: bool = False
    stage4_comparator_invoked: bool = False
    thirty_day_gate_satisfied: bool = False
    prdv4_stage4_complete: bool = False
    operational_readiness: bool = False
    live_ready: bool = False
    shadow_ready: bool = False
    deribit_ready: bool = False
    production_execution: bool = False
    real_orders_enabled: bool = False
    real_money_enabled: bool = False
    real_capital_reserved: bool = False
    live_api_called: bool = False
    scheduler_enabled: bool = False
    auto_loop_enabled: bool = False
    connector_invoked: bool = False
    private_api_ready: bool = False
    real_wall_clock_used: bool = False
    real_account_equity_used: bool = False
    real_capital_used: bool = False


def _canonical_digest(payload: dict[str, object]) -> str:
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=True, allow_nan=False)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _is_plain_non_empty_string(value: object) -> bool:
    return (
        type(value) is str
        and value.strip() != ""
        and value == value.strip()
        and not any(ord(char) < 32 or ord(char) == 127 for char in value)
    )


def _is_hex64_string(value: object) -> bool:
    return type(value) is str and len(value) == _SHA256_HEX_LENGTH and all(char in _HEX_CHARS for char in value)


def _require_plain_non_empty_string(value: object, field_name: str) -> str:
    if not _is_plain_non_empty_string(value):
        raise PaperEdgeIdentityEvidenceError(f"paper_edge_identity_evidence:{field_name}_invalid")
    return value  # type: ignore[return-value]


def _derive_paper_edge_id(strategy_id: str, market_symbol: str) -> str:
    canonical = json.dumps(
        {"strategy_id": strategy_id, "market_symbol": market_symbol},
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _normalize_metadata(metadata: object) -> tuple[tuple[str, str], ...]:
    if metadata is None:
        return ()
    if not isinstance(metadata, Mapping):
        raise PaperEdgeIdentityEvidenceError("paper_edge_identity_evidence:metadata_malformed")
    items: list[tuple[str, str]] = []
    for key, value in metadata.items():
        if type(key) is not str or type(value) is not str:
            raise PaperEdgeIdentityEvidenceError("paper_edge_identity_evidence:metadata_malformed")
        if key != key.strip() or value != value.strip() or any(ord(char) < 32 or ord(char) == 127 for char in key):
            raise PaperEdgeIdentityEvidenceError("paper_edge_identity_evidence:metadata_malformed")
        if any(ord(char) < 32 or ord(char) == 127 for char in value):
            raise PaperEdgeIdentityEvidenceError("paper_edge_identity_evidence:metadata_malformed")
        items.append((key, value))
    return tuple(sorted(items))


def _metadata_texts(metadata: tuple[tuple[str, str], ...]) -> tuple[str, ...]:
    return tuple(text for pair in metadata for text in pair)


def _serialize_metadata(metadata: tuple[tuple[str, str], ...]) -> list[list[str]]:
    return [[key, value] for key, value in metadata]


def _has_scope_violation(*texts: object) -> bool:
    for text in texts:
        if type(text) is not str or text == "":
            continue
        if _BIST_PATTERN.search(text):
            return True
        scrubbed = text
        for safe_term in _SAFE_MARKET_DATA_TERMS:
            scrubbed = re.sub(re.escape(safe_term), " ", scrubbed, flags=re.IGNORECASE)
        if _FORBIDDEN_PATTERN.search(scrubbed):
            return True
    return False


def _has_clock_token(*texts: object) -> bool:
    for text in texts:
        if type(text) is not str or text == "":
            continue
        lowered = text.lower()
        if any(token in lowered for token in _CLOCK_TOKENS):
            return True
    return False


def _str_field(value: object) -> str:
    return value if type(value) is str else ""


def _spec_hard_failures(
    strategy_spec: StrategySpec, expected_strategy_spec_digest: str, market_symbol: str
) -> list[str]:
    hard: list[str] = []
    if type(strategy_spec.market_type) is not StrategySpecMarketType or strategy_spec.market_type not in (
        _SUPPORTED_MARKET_TYPES
    ):
        hard.append("paper_edge_identity_evidence:unsupported_market_type")

    try:
        recomputed = strategy_spec_digest(strategy_spec)
    except Exception:  # noqa: BLE001 - public digest recompute failures fail closed at this boundary
        recomputed = None
    if recomputed is None or recomputed != expected_strategy_spec_digest:
        hard.append("paper_edge_identity_evidence:strategy_spec_digest_mismatch")

    try:
        validation = validate_strategy_spec(strategy_spec_to_dict(strategy_spec))
        accepted = validation.accepted is True
    except Exception:  # noqa: BLE001 - a malformed forged spec must fail closed, never crash
        accepted = False
    if not accepted:
        hard.append("paper_edge_identity_evidence:strategy_spec_invalid")

    universe = strategy_spec.instrument_universe
    if (
        type(universe) is not tuple
        or not all(type(symbol) is str for symbol in universe)
        or market_symbol not in (universe)
    ):
        hard.append("paper_edge_identity_evidence:market_symbol_not_in_universe")
    return sorted(set(hard))


def _bridge_hard_failures(
    bridge: StrategySignalToPaperIntent,
    expected_signal_bridge_digest: str,
    strategy_spec: StrategySpec,
    expected_strategy_spec_digest: str,
    market_symbol: str,
    correlation_id: str,
) -> list[str]:
    hard: list[str] = []
    try:
        recomputed = strategy_signal_to_paper_intent_digest(bridge)
    except Exception:  # noqa: BLE001 - public digest recompute failures fail closed at this boundary
        recomputed = None
    if (
        recomputed is None
        or not _is_hex64_string(bridge.bridge_digest)
        or bridge.bridge_digest != recomputed
        or bridge.bridge_digest != expected_signal_bridge_digest
    ):
        hard.append("paper_edge_identity_evidence:signal_bridge_digest_mismatch")

    if bridge.status is not StrategySignalToPaperIntentStatus.READY or bridge.ready is not True:
        hard.append("paper_edge_identity_evidence:signal_bridge_not_ready")
    if (
        bridge.real_orders_enabled is not False
        or bridge.real_money_enabled is not False
        or bridge.capital_reserved is not False
        or bridge.order_routed is not False
        or bridge.execution_authorized is not False
        or bridge.live_api_called is not False
        or bridge.scheduler_enabled is not False
        or bridge.auto_loop_enabled is not False
        or bridge.connector_invoked is not False
        or bridge.live_ready is not False
        or bridge.shadow_ready is not False
        or bridge.profitability_proven is not False
        or bridge.edge_proven is not False
    ):
        hard.append("paper_edge_identity_evidence:signal_bridge_unsafe_flags")

    if bridge.strategy_id != strategy_spec.strategy_id:
        hard.append("paper_edge_identity_evidence:signal_bridge_strategy_id_mismatch")
    if bridge.strategy_version != strategy_spec.strategy_version:
        hard.append("paper_edge_identity_evidence:signal_bridge_strategy_version_mismatch")
    if bridge.spec_digest != expected_strategy_spec_digest:
        hard.append("paper_edge_identity_evidence:signal_bridge_spec_digest_mismatch")
    if bridge.correlation_id != correlation_id:
        hard.append("paper_edge_identity_evidence:signal_bridge_correlation_id_mismatch")
    if bridge.market_symbol != market_symbol:
        hard.append("paper_edge_identity_evidence:signal_bridge_market_symbol_mismatch")
    return sorted(set(hard))


def build_paper_edge_identity_evidence(
    strategy_spec: StrategySpec,
    *,
    expected_strategy_spec_digest: str,
    market_symbol: str,
    edge_identity_id: str,
    paper_id: str,
    correlation_id: str,
    signal_to_paper_intent: StrategySignalToPaperIntent | None = None,
    expected_signal_bridge_digest: str | None = None,
    metadata: Mapping[str, str] | None = None,
) -> PaperEdgeIdentityEvidence:
    """Resolve a deterministic, digest-bound paper edge identity from a proven StrategySpec (+ optional bridge)."""

    if type(strategy_spec) is not StrategySpec:
        raise PaperEdgeIdentityEvidenceError("paper_edge_identity_evidence:strategy_spec_malformed")
    if not _is_hex64_string(expected_strategy_spec_digest):
        raise PaperEdgeIdentityEvidenceError("paper_edge_identity_evidence:expected_strategy_spec_digest_invalid")
    market_symbol = _require_plain_non_empty_string(market_symbol, "market_symbol")
    edge_identity_id = _require_plain_non_empty_string(edge_identity_id, "edge_identity_id")
    paper_id = _require_plain_non_empty_string(paper_id, "paper_id")
    correlation_id = _require_plain_non_empty_string(correlation_id, "correlation_id")

    bridge_supplied = signal_to_paper_intent is not None
    if bridge_supplied:
        if type(signal_to_paper_intent) is not StrategySignalToPaperIntent:
            raise PaperEdgeIdentityEvidenceError("paper_edge_identity_evidence:signal_to_paper_intent_malformed")
        if not _is_hex64_string(expected_signal_bridge_digest):
            raise PaperEdgeIdentityEvidenceError("paper_edge_identity_evidence:expected_signal_bridge_digest_invalid")
    elif expected_signal_bridge_digest is not None:
        raise PaperEdgeIdentityEvidenceError("paper_edge_identity_evidence:expected_signal_bridge_digest_unexpected")

    metadata_pairs = _normalize_metadata(metadata)
    scope_texts = (market_symbol, edge_identity_id, paper_id, correlation_id, *_metadata_texts(metadata_pairs))
    if _has_scope_violation(*scope_texts):
        raise PaperEdgeIdentityEvidenceError("paper_edge_identity_evidence:scope_violation")
    if _has_clock_token(*scope_texts):
        raise PaperEdgeIdentityEvidenceError("paper_edge_identity_evidence:clock_token_forbidden")

    hard = _spec_hard_failures(strategy_spec, expected_strategy_spec_digest, market_symbol)
    if bridge_supplied:
        hard.extend(
            _bridge_hard_failures(
                signal_to_paper_intent,  # type: ignore[arg-type]
                expected_signal_bridge_digest,  # type: ignore[arg-type]
                strategy_spec,
                expected_strategy_spec_digest,
                market_symbol,
                correlation_id,
            )
        )
    hard = sorted(set(hard))

    strategy_id = _str_field(strategy_spec.strategy_id)
    if hard:
        status = PaperEdgeIdentityEvidenceStatus.REJECTED
        ready = False
        reason_codes = tuple(hard)
        paper_edge_id = ""
        verified_strategy_spec_digest = ""
        verified_signal_bridge_digest = ""
        binding_strength = _BINDING_UNRESOLVED
        signal_bridge_consumed = False
    else:
        status = PaperEdgeIdentityEvidenceStatus.READY
        ready = True
        reason_codes = ()
        paper_edge_id = _derive_paper_edge_id(strategy_id, market_symbol)
        verified_strategy_spec_digest = expected_strategy_spec_digest
        signal_bridge_consumed = bridge_supplied
        if bridge_supplied:
            binding_strength = _BINDING_SPEC_AND_BRIDGE
            verified_signal_bridge_digest = expected_signal_bridge_digest  # type: ignore[assignment]
        else:
            binding_strength = _BINDING_SPEC_ONLY
            verified_signal_bridge_digest = ""

    signal_bridge_digest = _str_field(signal_to_paper_intent.bridge_digest) if bridge_supplied else ""

    fields: dict[str, object] = {
        "schema_version": _SCHEMA_VERSION,
        "evidence_version": _EVIDENCE_VERSION,
        "status": status,
        "ready": ready,
        "edge_identity_id": edge_identity_id,
        "paper_id": paper_id,
        "correlation_id": correlation_id,
        "edge_identity_resolved": ready,
        "strategy_spec_identity_proven": ready,
        "signal_bridge_consumed": signal_bridge_consumed,
        "paper_edge_id": paper_edge_id,
        "edge_id_form": _EDGE_ID_FORM,
        "edge_id_derivation_policy": _EDGE_ID_DERIVATION_POLICY,
        "edge_id_derivation_inputs": _EDGE_ID_DERIVATION_INPUTS,
        "strategy_id": strategy_id,
        "strategy_version": _str_field(strategy_spec.strategy_version),
        "strategy_family": _str_field(strategy_spec.strategy_family),
        "edge_family": _str_field(strategy_spec.edge_family),
        "market_type": strategy_spec.market_type.value
        if type(strategy_spec.market_type) is StrategySpecMarketType
        else "",
        "market_symbol": market_symbol,
        "expected_strategy_spec_digest": expected_strategy_spec_digest,
        "verified_strategy_spec_digest": verified_strategy_spec_digest,
        "signal_bridge_digest": signal_bridge_digest,
        "expected_signal_bridge_digest": expected_signal_bridge_digest if bridge_supplied else "",
        "verified_signal_bridge_digest": verified_signal_bridge_digest,
        "binding_strength": binding_strength,
        "paper_chain_link": _PAPER_CHAIN_LINK,
        "paper_chain_link_cryptographic": False,
        "paper_chain_spec_digest_carried": False,
        "paper_chain_link_limitation": _PAPER_CHAIN_LINK_LIMITATION,
        "reason_codes": reason_codes,
        "metadata": metadata_pairs,
    }
    seed = PaperEdgeIdentityEvidence(edge_identity_digest="", **fields)  # type: ignore[arg-type]
    return _replace_evidence_digest(seed, paper_edge_identity_evidence_digest(seed))


def _replace_evidence_digest(evidence: PaperEdgeIdentityEvidence, digest: str) -> PaperEdgeIdentityEvidence:
    fields = _evidence_fields(evidence)
    fields["edge_identity_digest"] = digest
    return PaperEdgeIdentityEvidence(**fields)  # type: ignore[arg-type]


def _evidence_fields(evidence: PaperEdgeIdentityEvidence) -> dict[str, object]:
    return {
        "schema_version": evidence.schema_version,
        "evidence_version": evidence.evidence_version,
        "status": evidence.status,
        "ready": evidence.ready,
        "edge_identity_id": evidence.edge_identity_id,
        "paper_id": evidence.paper_id,
        "correlation_id": evidence.correlation_id,
        "edge_identity_resolved": evidence.edge_identity_resolved,
        "strategy_spec_identity_proven": evidence.strategy_spec_identity_proven,
        "signal_bridge_consumed": evidence.signal_bridge_consumed,
        "paper_edge_id": evidence.paper_edge_id,
        "edge_id_form": evidence.edge_id_form,
        "edge_id_derivation_policy": evidence.edge_id_derivation_policy,
        "edge_id_derivation_inputs": evidence.edge_id_derivation_inputs,
        "strategy_id": evidence.strategy_id,
        "strategy_version": evidence.strategy_version,
        "strategy_family": evidence.strategy_family,
        "edge_family": evidence.edge_family,
        "market_type": evidence.market_type,
        "market_symbol": evidence.market_symbol,
        "expected_strategy_spec_digest": evidence.expected_strategy_spec_digest,
        "verified_strategy_spec_digest": evidence.verified_strategy_spec_digest,
        "signal_bridge_digest": evidence.signal_bridge_digest,
        "expected_signal_bridge_digest": evidence.expected_signal_bridge_digest,
        "verified_signal_bridge_digest": evidence.verified_signal_bridge_digest,
        "binding_strength": evidence.binding_strength,
        "paper_chain_link": evidence.paper_chain_link,
        "paper_chain_link_cryptographic": evidence.paper_chain_link_cryptographic,
        "paper_chain_spec_digest_carried": evidence.paper_chain_spec_digest_carried,
        "paper_chain_link_limitation": evidence.paper_chain_link_limitation,
        "reason_codes": evidence.reason_codes,
        "metadata": evidence.metadata,
    }


def _evidence_payload_from(evidence: PaperEdgeIdentityEvidence) -> dict[str, object]:
    return {
        "schema_version": evidence.schema_version,
        "evidence_version": evidence.evidence_version,
        "status": evidence.status.value,
        "ready": evidence.ready,
        "edge_identity_id": evidence.edge_identity_id,
        "paper_id": evidence.paper_id,
        "correlation_id": evidence.correlation_id,
        "edge_identity_resolved": evidence.edge_identity_resolved,
        "strategy_spec_identity_proven": evidence.strategy_spec_identity_proven,
        "signal_bridge_consumed": evidence.signal_bridge_consumed,
        "paper_edge_id": evidence.paper_edge_id,
        "edge_id_form": evidence.edge_id_form,
        "edge_id_derivation_policy": evidence.edge_id_derivation_policy,
        "edge_id_derivation_inputs": list(evidence.edge_id_derivation_inputs),
        "strategy_id": evidence.strategy_id,
        "strategy_version": evidence.strategy_version,
        "strategy_family": evidence.strategy_family,
        "edge_family": evidence.edge_family,
        "market_type": evidence.market_type,
        "market_symbol": evidence.market_symbol,
        "expected_strategy_spec_digest": evidence.expected_strategy_spec_digest,
        "verified_strategy_spec_digest": evidence.verified_strategy_spec_digest,
        "signal_bridge_digest": evidence.signal_bridge_digest,
        "expected_signal_bridge_digest": evidence.expected_signal_bridge_digest,
        "verified_signal_bridge_digest": evidence.verified_signal_bridge_digest,
        "binding_strength": evidence.binding_strength,
        "paper_chain_link": evidence.paper_chain_link,
        "paper_chain_link_cryptographic": evidence.paper_chain_link_cryptographic,
        "paper_chain_spec_digest_carried": evidence.paper_chain_spec_digest_carried,
        "paper_chain_link_limitation": evidence.paper_chain_link_limitation,
        "reason_codes": list(evidence.reason_codes),
        "metadata": _serialize_metadata(evidence.metadata),
        "paper_only": evidence.paper_only,
        "edge_proven": evidence.edge_proven,
        "profitability_proven": evidence.profitability_proven,
        "same_edge_as_backtest_proven": evidence.same_edge_as_backtest_proven,
        "same_edge_comparison_ready": evidence.same_edge_comparison_ready,
        "comparison_ready": evidence.comparison_ready,
        "paper_vs_backtest_comparison_ready": evidence.paper_vs_backtest_comparison_ready,
        "stage4_comparator_invoked": evidence.stage4_comparator_invoked,
        "thirty_day_gate_satisfied": evidence.thirty_day_gate_satisfied,
        "prdv4_stage4_complete": evidence.prdv4_stage4_complete,
        "operational_readiness": evidence.operational_readiness,
        "live_ready": evidence.live_ready,
        "shadow_ready": evidence.shadow_ready,
        "deribit_ready": evidence.deribit_ready,
        "production_execution": evidence.production_execution,
        "real_orders_enabled": evidence.real_orders_enabled,
        "real_money_enabled": evidence.real_money_enabled,
        "real_capital_reserved": evidence.real_capital_reserved,
        "live_api_called": evidence.live_api_called,
        "scheduler_enabled": evidence.scheduler_enabled,
        "auto_loop_enabled": evidence.auto_loop_enabled,
        "connector_invoked": evidence.connector_invoked,
        "private_api_ready": evidence.private_api_ready,
        "real_wall_clock_used": evidence.real_wall_clock_used,
        "real_account_equity_used": evidence.real_account_equity_used,
        "real_capital_used": evidence.real_capital_used,
    }


def paper_edge_identity_evidence_to_dict(evidence: PaperEdgeIdentityEvidence) -> dict[str, object]:
    """Canonical JSON-ready mapping for the paper edge-identity evidence, including its self-digest."""

    payload = _evidence_payload_from(evidence)
    payload["edge_identity_digest"] = evidence.edge_identity_digest
    return payload


def paper_edge_identity_evidence_digest(evidence: PaperEdgeIdentityEvidence) -> str:
    """Recompute the canonical edge-identity digest, excluding only the self-digest field."""

    return _canonical_digest(_evidence_payload_from(evidence))


__all__ = [
    "PaperEdgeIdentityEvidence",
    "PaperEdgeIdentityEvidenceError",
    "PaperEdgeIdentityEvidenceStatus",
    "build_paper_edge_identity_evidence",
    "paper_edge_identity_evidence_digest",
    "paper_edge_identity_evidence_to_dict",
]
