"""
Deterministic self-optimizer: read validation JSON, update env knobs, write optimizer_env.ps1.

Exit codes: 0 = stop (success or max iter), 1 = run another iteration.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict

_REPO = Path(__file__).resolve().parents[3]
_TOOLS = _REPO / "tools"
_STATE_PATH = _TOOLS / "optimizer_state.json"
_ENV_PATH = _TOOLS / "optimizer_env.ps1"
_HISTORY_PATH = _TOOLS / "optimizer_history.json"
_FINAL_REPORT = _TOOLS / "auto_optimize_report.json"

_DEFAULT_STATE: Dict[str, str] = {
    "BIST_REALISM_MIN_FILL_RATIO": "0.22",
    "BIST_REALISM_MISS_MIX_THRESHOLD": "0.48",
    "BIST_REALISM_BORDER_FILL_MAX": "0.42",
    "BIST_REALISM_SLIP_MULT": "1.0",
    "BIST_EXEC_MIN_FILL_PROB": "0.34",
    "BIST_EXEC_SLIP_SCALE": "1.0",
    "BIST_EXEC_FILL_PROB_MULT": "1.0",
    "BIST_PORTFOLIO_MIN_CONF_MULT": "1.0",
    "BIST_PORTFOLIO_RISK_BUDGET": "0.05",
    "BIST_RISK_COMBINED_MULT": "1.0",
    "BIST_ADAPTIVE_THRESHOLD_MULT": "1.0",
}

_ENV_ORDER = list(_DEFAULT_STATE.keys())


def _f(s: str, d: float) -> float:
    try:
        return float(s)
    except (TypeError, ValueError):
        return d


def _clamp_str(val: float, lo: float, hi: float) -> str:
    return str(max(lo, min(hi, val)))


def load_state() -> Dict[str, str]:
    if _STATE_PATH.is_file():
        raw = json.loads(_STATE_PATH.read_text(encoding="utf-8"))
        if isinstance(raw, dict):
            out = dict(_DEFAULT_STATE)
            for k, v in raw.items():
                if isinstance(k, str) and isinstance(v, str):
                    out[k] = v
            return out
    return dict(_DEFAULT_STATE)


def save_state(state: Dict[str, str]) -> None:
    _TOOLS.mkdir(parents=True, exist_ok=True)
    _STATE_PATH.write_text(json.dumps(state, indent=2), encoding="utf-8")


def write_ps1(state: Dict[str, str]) -> None:
    lines = [
        "# Auto-generated by bist_core.validation.auto_optimizer — do not edit by hand.",
        "# Deterministic env overrides for next validation run.",
    ]
    for k in _ENV_ORDER:
        if k in state:
            v = state[k].replace('"', '`"')
            lines.append(f'$env:{k} = "{v}"')
    _ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def apply_fixes(system_type: str, state: Dict[str, str]) -> Dict[str, str]:
    """Minimal deterministic deltas per SYSTEM_TYPE."""
    s = dict(state)

    def g(key: str, default: float) -> float:
        return _f(s.get(key, str(default)), default)

    if system_type == "FAKE_EDGE":
        s["BIST_REALISM_MIN_FILL_RATIO"] = _clamp_str(
            g("BIST_REALISM_MIN_FILL_RATIO", 0.22) + 0.02, 0.08, 0.45
        )
        s["BIST_REALISM_MISS_MIX_THRESHOLD"] = _clamp_str(
            g("BIST_REALISM_MISS_MIX_THRESHOLD", 0.48) - 0.06, 0.05, 0.85
        )
        s["BIST_REALISM_SLIP_MULT"] = _clamp_str(
            g("BIST_REALISM_SLIP_MULT", 1.0) + 0.06, 0.5, 1.5
        )
        s["BIST_EXEC_MIN_FILL_PROB"] = _clamp_str(
            g("BIST_EXEC_MIN_FILL_PROB", 0.34) + 0.03, 0.2, 0.55
        )
        s["BIST_EXEC_FILL_PROB_MULT"] = _clamp_str(
            g("BIST_EXEC_FILL_PROB_MULT", 1.0) - 0.04, 0.70, 1.15
        )
    elif system_type == "LOW_SIGNAL_SYSTEM":
        s["BIST_PORTFOLIO_MIN_CONF_MULT"] = _clamp_str(
            g("BIST_PORTFOLIO_MIN_CONF_MULT", 1.0) * 0.96, 0.80, 1.20
        )
        s["BIST_ADAPTIVE_THRESHOLD_MULT"] = _clamp_str(
            g("BIST_ADAPTIVE_THRESHOLD_MULT", 1.0) * 0.97, 0.88, 1.08
        )
    elif system_type == "UNDER_TRADING_SYSTEM":
        s["BIST_ADAPTIVE_THRESHOLD_MULT"] = _clamp_str(
            g("BIST_ADAPTIVE_THRESHOLD_MULT", 1.0) * 0.93, 0.88, 1.08
        )
        s["BIST_PORTFOLIO_MIN_CONF_MULT"] = _clamp_str(
            g("BIST_PORTFOLIO_MIN_CONF_MULT", 1.0) * 0.92, 0.80, 1.20
        )
    elif system_type == "UNSTABLE_SYSTEM":
        s["BIST_RISK_COMBINED_MULT"] = _clamp_str(
            g("BIST_RISK_COMBINED_MULT", 1.0) * 0.88, 0.45, 1.0
        )
        s["BIST_PORTFOLIO_RISK_BUDGET"] = _clamp_str(
            g("BIST_PORTFOLIO_RISK_BUDGET", 0.05) * 0.90, 0.02, 0.08
        )
    elif system_type == "REAL_EDGE":
        s["BIST_EXEC_SLIP_SCALE"] = _clamp_str(
            g("BIST_EXEC_SLIP_SCALE", 1.0) * 1.02, 0.65, 1.35
        )
        s["BIST_RISK_COMBINED_MULT"] = _clamp_str(
            g("BIST_RISK_COMBINED_MULT", 1.0) * 0.98, 0.45, 1.0
        )
    elif system_type == "INCOMPLETE_RUN":
        # No logic change — encourage completion via env already in run script
        pass
    return s


def append_history(entry: dict[str, Any]) -> None:
    hist: list[Any] = []
    if _HISTORY_PATH.is_file():
        try:
            hist = json.loads(_HISTORY_PATH.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            hist = []
    if not isinstance(hist, list):
        hist = []
    hist.append(entry)
    _HISTORY_PATH.write_text(json.dumps(hist, indent=2, default=str), encoding="utf-8")


def run_step(
    analysis_path: Path,
    iteration: int,
    max_iterations: int,
) -> int:
    if not analysis_path.is_file():
        print(json.dumps({"error": "analysis_missing", "path": str(analysis_path)}))
        return 2

    data = json.loads(analysis_path.read_text(encoding="utf-8"))
    diag = data.get("diagnosis") or {}
    system_type = str(diag.get("SYSTEM_TYPE", "UNKNOWN"))
    conf = float(diag.get("EDGE_CONFIDENCE", 0.0) or 0.0)

    state = load_state()
    new_state = apply_fixes(system_type, state)
    save_state(new_state)
    write_ps1(new_state)

    append_history(
        {
            "iteration": iteration,
            "SYSTEM_TYPE": system_type,
            "EDGE_CONFIDENCE": conf,
            "failure_flags": data.get("failure_flags"),
            "derived_metrics": data.get("derived_metrics"),
            "state_after": new_state,
        }
    )

    if system_type == "REAL_EDGE" and conf >= 0.75:
        _write_final_report(system_type, conf, iteration, "target_reached")
        print("SYSTEM AUTO-OPTIMIZATION COMPLETE")
        return 0

    if iteration >= max_iterations:
        _write_final_report(system_type, conf, iteration, "max_iterations")
        print("SYSTEM AUTO-OPTIMIZATION COMPLETE")
        return 0

    return 1


def _write_final_report(
    system_type: str,
    conf: float,
    iterations: int,
    reason: str,
) -> None:
    hist: list[Any] = []
    if _HISTORY_PATH.is_file():
        try:
            hist = json.loads(_HISTORY_PATH.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            hist = []
    improvements: list[str] = []
    for h in hist:
        if isinstance(h, dict) and h.get("state_after"):
            improvements.append(
                f"iter{h.get('iteration')}: {h.get('SYSTEM_TYPE')} conf={h.get('EDGE_CONFIDENCE')}"
            )
    weakness = ""
    if hist and isinstance(hist[-1], dict):
        d = hist[-1]
        weakness = str(d.get("failure_flags") or "")

    out = {
        "FINAL_SYSTEM_TYPE": system_type,
        "EDGE_CONFIDENCE": round(conf, 6),
        "TOTAL_ITERATIONS": int(iterations),
        "IMPROVEMENTS": improvements,
        "FINAL_WEAKNESS": weakness,
        "stop_reason": reason,
    }
    _FINAL_REPORT.write_text(json.dumps(out, indent=2), encoding="utf-8")
    print(json.dumps(out, indent=2))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--analysis", type=Path, required=True)
    ap.add_argument("--iteration", type=int, default=1)
    ap.add_argument("--max-iterations", type=int, default=3)
    args = ap.parse_args()
    code = run_step(args.analysis, args.iteration, args.max_iterations)
    sys.exit(code)


if __name__ == "__main__":
    main()
