"""FAZ599: Weekly review pack — offline, deterministic summary.

Scans execution summaries and daily reports, then writes a markdown
summary per ISO week under data/log/review/<YYYY-WW>/summary.md.

No network, no secrets. Filesystem-only.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Iterable, List, Optional


REPO_ROOT = Path(__file__).resolve().parents[3]
LOG_ROOT = REPO_ROOT / "data" / "log"
EXEC_ROOT = LOG_ROOT / "execution"
REPORTS_ROOT = LOG_ROOT / "reports"
REVIEW_ROOT = LOG_ROOT / "review"


@dataclass(frozen=True)
class DaySummary:
    day: str
    has_execution: bool
    has_report: bool
    execution_path: Optional[Path]
    report_path: Optional[Path]
    realized_pnl_try: Optional[float]
    n_fills: Optional[int]


def _iter_days(root: Path) -> Iterable[str]:
    if not root.exists():
        return []
    for child in sorted(root.iterdir()):
        if not child.is_dir():
            continue
        name = child.name
        if len(name) == 10 and name[4] == "-" and name[7] == "-":
            yield name


def _iso_week_for_day(day: str) -> str:
    d = datetime.strptime(day, "%Y-%m-%d").date()
    year, week, _ = d.isocalendar()
    return f"{year:04d}-{week:02d}"


def _target_week(weeks_back: int) -> str:
    today = date.today() - timedelta(weeks=weeks_back)
    year, week, _ = today.isocalendar()
    return f"{year:04d}-{week:02d}"


def _load_execution_summary(path: Path) -> tuple[Optional[float], Optional[int]]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None, None
    realized = data.get("realized_pnl_try")
    n_fills = data.get("n_fills")
    try:
        realized_f = float(realized) if realized is not None else None
    except (TypeError, ValueError):
        realized_f = None
    try:
        n_fills_i = int(n_fills) if n_fills is not None else None
    except (TypeError, ValueError):
        n_fills_i = None
    return realized_f, n_fills_i


def collect_week(week_id: str) -> List[DaySummary]:
    days_exec = set(_iter_days(EXEC_ROOT))
    days_reports = set(_iter_days(REPORTS_ROOT))
    days = sorted(days_exec | days_reports)

    out: List[DaySummary] = []
    for day in days:
        if _iso_week_for_day(day) != week_id:
            continue

        exec_path = EXEC_ROOT / day / "execution_summary.json"
        report_path = REPORTS_ROOT / day / "summary.html"

        has_exec = exec_path.is_file()
        has_rep = report_path.is_file()

        realized_pnl: Optional[float]
        n_fills: Optional[int]
        if has_exec:
            realized_pnl, n_fills = _load_execution_summary(exec_path)
        else:
            realized_pnl, n_fills = None, None

        out.append(
            DaySummary(
                day=day,
                has_execution=has_exec,
                has_report=has_rep,
                execution_path=exec_path if has_exec else None,
                report_path=report_path if has_rep else None,
                realized_pnl_try=realized_pnl,
                n_fills=n_fills,
            )
        )

    return out


def render_markdown(week_id: str, days: List[DaySummary]) -> str:
    lines: List[str] = []
    lines.append(f"# Weekly review {week_id}")
    lines.append("")
    if not days:
        lines.append("_No days with execution/report artifacts found for this week._")
        lines.append("")
        return "\n".join(lines)

    lines.append("| Day | Report | Execution | Fills | Realized PnL (TRY) |")
    lines.append("|-----|--------|-----------|-------|---------------------|")
    for d in days:
        report_col = "yes" if d.has_report else "no"
        exec_col = "yes" if d.has_execution else "no"
        fills_col = str(d.n_fills) if d.n_fills is not None else "-"
        pnl_col = f"{d.realized_pnl_try:.2f}" if d.realized_pnl_try is not None else "-"
        lines.append(f"| {d.day} | {report_col} | {exec_col} | {fills_col} | {pnl_col} |")

    lines.append("")
    lines.append("Generated by `bist_core.review.weekly` (offline, filesystem-only).")
    lines.append("")
    return "\n".join(lines)


def write_week_summary(week_id: str, days: List[DaySummary]) -> Path:
    week_dir = REVIEW_ROOT / week_id
    week_dir.mkdir(parents=True, exist_ok=True)
    out_path = week_dir / "summary.md"
    content = render_markdown(week_id, days)
    out_path.write_text(content, encoding="utf-8")
    return out_path


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="FAZ599: Weekly review pack (offline, deterministic).")
    parser.add_argument(
        "--weeks-back",
        type=int,
        default=0,
        help="How many weeks back from current week (0=this week, 1=previous, ...).",
    )
    args = parser.parse_args(argv)

    if args.weeks_back < 0:
        print("weeks-back must be >= 0")
        return 2

    week_id = _target_week(args.weeks_back)
    days = collect_week(week_id)
    out_path = write_week_summary(week_id, days)
    print(f"weekly_review: week={week_id} days={len(days)} out={out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
