# Auto-generated by bist_core.validation.auto_optimizer — do not edit by hand.
# Deterministic env overrides for next validation run.
$env:BIST_REALISM_MIN_FILL_RATIO = "0.22"
$env:BIST_REALISM_MISS_MIX_THRESHOLD = "0.48"
$env:BIST_REALISM_BORDER_FILL_MAX = "0.42"
$env:BIST_REALISM_SLIP_MULT = "1.0"
$env:BIST_EXEC_MIN_FILL_PROB = "0.34"
$env:BIST_EXEC_SLIP_SCALE = "1.0"
$env:BIST_EXEC_FILL_PROB_MULT = "1.0"
$env:BIST_PORTFOLIO_MIN_CONF_MULT = "0.8"
$env:BIST_PORTFOLIO_RISK_BUDGET = "0.05"
$env:BIST_RISK_COMBINED_MULT = "1.0"
$env:BIST_ADAPTIVE_THRESHOLD_MULT = "0.88"
